// Generated by CoffeeScript 1.3.3
(function() {
  var icon_d, icon_e, inputElement, processInput, processedInputs, processing, _i, _len, _ref,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  icon_e = "url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9kMEA8UMRggzYsAAAMbSURBVDjLbZNtTFN3FMZ/9/b2DdsKV2CzIiiUWBHUYITNucg06lzUqDMQk1WzIB+WuCWLmmUvbjrGJGzJNjOyl2xGExI/GF2UJaKJG0qYonNTjFaFBZVhow5pi720t733vy/XjBHP5/PLeZ6T55F4+tiBNMDXzfN2lkz1tExRHZw4G+NGz30OnR2SnixKT4FlwHy7fnpVzYK8nq7uOLFBg2Cxm8Urczn88z2uXktw8nJEAmy2CbAEiMadlW82bas+WjQpQ6U/RkCVGOhL0/37KME5Xvr7Nar8kuiNpDqViZcPtL4kVi4NEXuskIj/Ta5/CId8ivbe5O4rA3pXlSf7tBAG2ZOz9lz95dt9ynj4ra3lO8qLqnFEZVIij7zlITqONb6/trbvC2AMoDE/gM+ncG9EYyQpliqAAmTq1hcvKXE5PisQcXAVkFO2jI/2vLtq76fNHZY1+5a6QMBnwjNOBW+hnYSWyZEBE8hqbijtLJLjGKMPUOcv4oNd79VYsGIpTG/fEryeTMoU+ifx3Nwcsh3ybRkwWz95saEo34tLMjAVwZG2lm0tLXvPWLAJGLUbSoMVC+dg95ZSPNUkbUg8vzbULQPOxUHXl5f+GODyoKC3L8LG0O5W66oBCMD21ed1YTFlE+4siek2SAoNICkPDX+38fu2O3Se+gfDVPix/eaqcY8VgLhy8cPMszM3o93V0Pv7cOa7OBEemQVIivQ43vZgREeY4PakOXp+uOvJYwF775/f6BXzVjMWdZOK/Mbk7BRhr3vXweOjtwBFVgvg1eV5pBMGF/+KAySAzOv1lQvvD+7QK+YvQxu2oQ3cwDncyVhA5pXQuSZLYUa5Ho4vqVnnORMby8V5V2XNazPXLQpO+6m6YBSBSlovRX8UxvHwCLbCQcrmXvBZ1v7rQtP2MjHN5SaFQUB1Uq4+JIMH9YWt6JqEL36Ba5FblNf1eCyF/8u+DTA3r5hhOqIa+T4nm152oc5wYVf96Mko7eej9W98fHP/+L5MbKMEiH31s2sWzFZ/vRR+RElxDgnF11D7TscP1o7NyoQYr+BfNwQwlc1KsPsAAAAASUVORK5CYII=)";

  icon_d = "url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9oBBhAPChwRtSQAAAMBSURBVDjLbZNPSGNXGMXPvbnJyzOJTF/k+QdCBMVO405Sl84w5S1mJ9KNS2lRhEo37aoMt3cW3XTRMtCdioiuDEFw4UB8sZhVs3EhtigEqggxxoQYXtL3z3dnM4FU5qy+xfnxfZyPA3xCnPNwb97f3/+xUCjIk5MTmcvl5Pr6uuz3kk/AVAgRbG9vz+q6/lej0YDneUgkEhgaGsLNzQ3a7TZWV1cJ5zxEnsBECCFzudxaJpN5Z9s2LMuCbdtotVpwHAeDg4OoVqsghPCVlZW39MlmeXh4KLPZ7LtEIoF4PA5d16GqKjzP+/nh4eErxhiklFAURVQqlWes/+zd3d0fRkdHQSkFYwwTExM4PT396ejo6DchxH8AYJomwuEwbNuG7/uvKOecCSGCjY2NF7FY7NdQKARFUaDrOorF4utsNvsLAJtzHt7a2vqCMQZFURCPx+H7/mcUQMA5H5ienv6TMQbXdZFMJlEsFl8ahvGec84AUCGENzU19XcQBBgYGICmaWCM/UsA4ODg4Pvx8fHfr6+vMTw8jCAIvpudnf3jIxwIIYLNzc3nc3Nz/zSbTdTrdQBAuVxWCedcMQzDdl0X9XodmqbBMAzCOacAej+ni4uL/tjYGC4vL9FqtWBZFubn5wlbWlr6ulQqIRKJAAAqlcrrHiSE8AHg7OzMT6VSsG0b3W4XjDHc3d19zjkn1PO8HcdxYNs2XNdFtVotfQzW55yHLy4u5OTkJCil6HQ6oJTC87w3y8vLlwBC5OrqSp6fn6NWq8GyLKytrREA2NnZ+XJmZqacTqdBCEGn00GtVkOz2YRpmhQAEUIEtN1uv0gmk9A0DZqmIZ/Pz5dKJZnJZMqqqiIajcJ1XTQaDTiOA9M0B4UQspcPAYC9vT2pqioeHx8Ri8UQiURAKUUqlYKUEt1uF/f39zBNMy6E6PyvTJzzEIAgnU4HUkpEo1GMjIwgEokgGo3C8zzc3t5+s7CwsNnfl6cNJACQz+dfHh8fy3w+LwuFgiwUCt/2eUI9X78+ADancwD8pkrXAAAAAElFTkSuQmCC)";

  processedInputs = [];

  processInput = function(oldInput) {
    var copyAttributes, enabled, newId, newInput, setEnabled, _ref;
    if (_ref = oldInput.get(0), __indexOf.call(processedInputs, _ref) >= 0) {
      return;
    }
    newInput = $(document.createElement("input"));
    processedInputs.push(oldInput.get(0), newInput.get(0));
    newId = "passwordMaker" + Math.random();
    newInput.attr("name", "");
    newInput.attr("id", newId);
    newInput.attr("type", "password");
    newInput.attr("tabindex", oldInput.attr("tabindex"));
    newInput.css("background-position", "right center");
    newInput.css("background-repeat", "no-repeat");
    copyAttributes = function() {
      var attrName, i, name, sourceStyle, targetStyle, _i, _j, _len, _ref1, _ref2, _results;
      _ref1 = ["size", "maxlength", "tabindex", "placeholder"];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        attrName = _ref1[_i];
        newInput.attr(attrName, oldInput.attr(attrName));
      }
      sourceStyle = window.getComputedStyle(oldInput.get(0));
      targetStyle = newInput.get(0).style;
      _results = [];
      for (i = _j = 0, _ref2 = sourceStyle.length; 0 <= _ref2 ? _j < _ref2 : _j > _ref2; i = 0 <= _ref2 ? ++_j : --_j) {
        name = sourceStyle.item(i);
        if (name !== "display" && name !== "background-position" && name !== "background-repeat" && name !== "background-image") {
          if (!(name.slice(0, 6) === "border" && sourceStyle.getPropertyValue("border-style") === "inset")) {
            _results.push(targetStyle.setProperty(name, sourceStyle.getPropertyValue(name)));
          } else {
            _results.push(void 0);
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
    copyAttributes();
    (function() {
      var observer, parent, _i, _len, _ref1;
      observer = new WebKitMutationObserver(copyAttributes);
      observer.observe(oldInput.get(0), {
        attributes: true,
        subtree: false
      });
      _ref1 = oldInput.parents();
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        parent = _ref1[_i];
        observer.observe(parent, {
          attributes: true,
          subtree: false
        });
      }
      return $(window).on("beforeunload", function() {
        observer.disconnect();
        $(window).off("beforeunload");
        return null;
      });
    })();
    enabled = true;
    setEnabled = function(value) {
      enabled = value;
      newInput.css("background-image", enabled ? icon_e : icon_d);
      return newInput.triggerHandler("input");
    };
    setEnabled(oldInput.val() === "");
    oldInput.attr("tabIndex", null);
    oldInput.css("display", "none");
    $("label[for=" + oldInput.attr("id") + "]").attr("for", newId);
    newInput.insertAfter(oldInput);
    oldInput.on("change", function() {
      if (oldInput.val() !== "" && newInput.val() === "") {
        newInput.val(oldInput.val());
        return setEnabled(false);
      }
    });
    newInput.on("mousemove", function(event) {
      return $(this).css("cursor", $(this).innerWidth() - event.offsetX < 16 ? "pointer" : "auto");
    });
    newInput.on("mousedown", function(event) {
      if (newInput.innerWidth() - event.offsetX < 16) {
        setEnabled(!enabled);
        return event.preventDefault();
      }
    });
    newInput.on("keydown", function(event) {
      if (event.ctrlKey && event.keyCode === 80) {
        setEnabled(!enabled);
        return event.preventDefault();
      }
    });
    newInput.on("focus blur", function(origEvent) {
      var event;
      event = document.createEvent("Event");
      event.initEvent(origEvent.type, true, true);
      return oldInput.get(0).dispatchEvent(event);
    });
    return newInput.on("input", function(event) {
      return oldInput.val(newInput.val() === "" ? "" : enabled ? makePassword(filterUrl(window.location.href), newInput.val(), "", "md5", "off", "1", "8", "", "", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789`~!@#$%^&*()_-+={}|[]\\:\";'<>?,./", "") : newInput.val());
    });
  };

  _ref = $('input[type=password]');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    inputElement = _ref[_i];
    processInput($(inputElement));
  }

  processing = false;

  $(document).on("DOMNodeInserted", function(event) {
    if (event.target.tagName === "INPUT" && event.target.type === "password" && !processing) {
      processing = true;
      processInput($(event.target));
      return processing = false;
    }
  });

}).call(this);
