// Generated by CoffeeScript 1.3.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  window.filterUrl = function(str) {
    var hasSLD, parts, uri, _ref;
    uri = parseUri(str);
    parts = uri.host.split(".");
    hasSLD = (_ref = [""].concat(parts.slice(Math.max(parts.length - 2, 0))).join("."), __indexOf.call(SLDs, _ref) >= 0);
    return parts.slice(parts.length - (hasSLD ? 3 : 2)).join(".");
  };

}).call(this);
